import type { Metadata } from "next";
import Header from "../components/Header";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

import "./globals.css";

export const metadata: Metadata = {
  title: "야놀자리서치",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <header>
          <Header />
        </header>
        {children}
      </body>
    </html>
  );
}
